// from input
pub fn run(inputs: &[u8]) -> i64 {
    let mut w: i64;
    let mut x: i64 = 0;
    let mut y: i64 = 0;
    let mut z: i64 = 0;

    w = *inputs.get(0).unwrap() as i64;
    x *= 0;
    x += z;
    x %= 26;
    z /= 1;
    x += 12;
    x = if x == w { 1 } else { 0 };
    x = if x == 0 { 1 } else { 0 };
    y *= 0;
    y += 25;
    y *= x;
    y += 1;
    z *= y;
    y *= 0;
    y += w;
    y += 1;
    y *= x;
    z += y;
    w = *inputs.get(1).unwrap() as i64;
    x *= 0;
    x += z;
    x %= 26;
    z /= 1;
    x += 13;
    x = if x == w { 1 } else { 0 };
    x = if x == 0 { 1 } else { 0 };
    y *= 0;
    y += 25;
    y *= x;
    y += 1;
    z *= y;
    y *= 0;
    y += w;
    y += 9;
    y *= x;
    z += y;
    w = *inputs.get(2).unwrap() as i64;
    x *= 0;
    x += z;
    x %= 26;
    z /= 1;
    x += 12;
    x = if x == w { 1 } else { 0 };
    x = if x == 0 { 1 } else { 0 };
    y *= 0;
    y += 25;
    y *= x;
    y += 1;
    z *= y;
    y *= 0;
    y += w;
    y += 11;
    y *= x;
    z += y;
    w = *inputs.get(3).unwrap() as i64;
    x *= 0;
    x += z;
    x %= 26;
    z /= 26;
    x += -13;
    x = if x == w { 1 } else { 0 };
    x = if x == 0 { 1 } else { 0 };
    y *= 0;
    y += 25;
    y *= x;
    y += 1;
    z *= y;
    y *= 0;
    y += w;
    y += 6;
    y *= x;
    z += y;
    w = *inputs.get(4).unwrap() as i64;
    x *= 0;
    x += z;
    x %= 26;
    z /= 1;
    x += 11;
    x = if x == w { 1 } else { 0 };
    x = if x == 0 { 1 } else { 0 };
    y *= 0;
    y += 25;
    y *= x;
    y += 1;
    z *= y;
    y *= 0;
    y += w;
    y += 6;
    y *= x;
    z += y;
    w = *inputs.get(5).unwrap() as i64;
    x *= 0;
    x += z;
    x %= 26;
    z /= 1;
    x += 15;
    x = if x == w { 1 } else { 0 };
    x = if x == 0 { 1 } else { 0 };
    y *= 0;
    y += 25;
    y *= x;
    y += 1;
    z *= y;
    y *= 0;
    y += w;
    y += 13;
    y *= x;
    z += y;
    w = *inputs.get(6).unwrap() as i64;
    x *= 0;
    x += z;
    x %= 26;
    z /= 26;
    x += -14;
    x = if x == w { 1 } else { 0 };
    x = if x == 0 { 1 } else { 0 };
    y *= 0;
    y += 25;
    y *= x;
    y += 1;
    z *= y;
    y *= 0;
    y += w;
    y += 13;
    y *= x;
    z += y;
    w = *inputs.get(7).unwrap() as i64;
    x *= 0;
    x += z;
    x %= 26;
    z /= 1;
    x += 12;
    x = if x == w { 1 } else { 0 };
    x = if x == 0 { 1 } else { 0 };
    y *= 0;
    y += 25;
    y *= x;
    y += 1;
    z *= y;
    y *= 0;
    y += w;
    y += 5;
    y *= x;
    z += y;
    w = *inputs.get(8).unwrap() as i64;
    x *= 0;
    x += z;
    x %= 26;
    z /= 26;
    x += -8;
    x = if x == w { 1 } else { 0 };
    x = if x == 0 { 1 } else { 0 };
    y *= 0;
    y += 25;
    y *= x;
    y += 1;
    z *= y;
    y *= 0;
    y += w;
    y += 7;
    y *= x;
    z += y;
    w = *inputs.get(9).unwrap() as i64;
    x *= 0;
    x += z;
    x %= 26;
    z /= 1;
    x += 14;
    x = if x == w { 1 } else { 0 };
    x = if x == 0 { 1 } else { 0 };
    y *= 0;
    y += 25;
    y *= x;
    y += 1;
    z *= y;
    y *= 0;
    y += w;
    y += 2;
    y *= x;
    z += y;
    w = *inputs.get(10).unwrap() as i64;
    x *= 0;
    x += z;
    x %= 26;
    z /= 26;
    x += -9;
    x = if x == w { 1 } else { 0 };
    x = if x == 0 { 1 } else { 0 };
    y *= 0;
    y += 25;
    y *= x;
    y += 1;
    z *= y;
    y *= 0;
    y += w;
    y += 10;
    y *= x;
    z += y;
    w = *inputs.get(11).unwrap() as i64;
    x *= 0;
    x += z;
    x %= 26;
    z /= 26;
    x += -11;
    x = if x == w { 1 } else { 0 };
    x = if x == 0 { 1 } else { 0 };
    y *= 0;
    y += 25;
    y *= x;
    y += 1;
    z *= y;
    y *= 0;
    y += w;
    y += 14;
    y *= x;
    z += y;
    w = *inputs.get(12).unwrap() as i64;
    x *= 0;
    x += z;
    x %= 26;
    z /= 26;
    x += -6;
    x = if x == w { 1 } else { 0 };
    x = if x == 0 { 1 } else { 0 };
    y *= 0;
    y += 25;
    y *= x;
    y += 1;
    z *= y;
    y *= 0;
    y += w;
    y += 7;
    y *= x;
    z += y;
    w = *inputs.get(13).unwrap() as i64;
    x *= 0;
    x += z;
    x %= 26;
    z /= 26;
    x += -5;
    x = if x == w { 1 } else { 0 };
    x = if x == 0 { 1 } else { 0 };
    y *= 0;
    y += 25;
    y *= x;
    y += 1;
    z *= y;
    y *= 0;
    y += w;
    y += 1;
    y *= x;
    z += y;

    z
}
